### ISSUE TITLE
Java Error on execute graylog-collector

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/collector#34]
hi,
i installed the graylog-collector 0.2.2 on an SLED 11, Kernel "3.0.13-0.27-pae" in /usr/share/graylog-collector, updated collector.conf and want to start with "graylog-collector run -f ../config/collector.conf". Immediately i get the following error messages:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog/collector/cli/Main : Unsup                       ported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: org.graylog.collector.cli.Main. Program will exit.

On the Linux machine is some Java installed: java-1_6_0-openjdk

What's going wrong? what to do?

**Comment by bernd** [comment]
@plt-sun You need at least Java 1.7 for this, 1.6 will not work. Sorry, this is not documented yet!

**Comment by bernd** [comment]
We will document this. (See #25)

**Comment by plt-sun** [comment]
hi there, would be a good idea to document this info.
I installed "jre-7u79-linux-i586.rpm" and graylog collector can now start.
