### ISSUE TITLE
too many files opened / Cannot read modified file

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/collector#40]
since one week i use the collector to collect logfiles from my processmanagmentsystems (about 70 linux machines) and send to graylog server. the collector ist running on SLES 11.x. i had to log about 60 - 80 logfiles. in my collector.conf there are all files and paths defined, even if they are not exist.
i started the collector by a selfcreatet start/stop file in /etc/init.d/. all output from collector himself is going to a logfile in /var /log.
now it happened, that sometimes some machines get an error like this:
```
"2015-07-01T07:24:17.520Z,""	at org.graylog.collector.file.FileReaderService$FsChangeListener.pathCreated(FileReaderService.java:180) [graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.520Z,""	at org.graylog.collector.file.FileReaderService.followFile(FileReaderService.java:130) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.520Z,""	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.520Z,""	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.521Z,""	at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.521Z,""	at org.graylog.collector.file.FileReaderService.access$400(FileReaderService.java:41) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.521Z,""	at org.graylog.collector.file.FileReaderService.access$400(FileReaderService.java:41) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:24:17.521Z,""	at org.graylog.collector.file.FileReaderService.followFile(FileReaderService.java:130) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
2015-07-01T07:24:17.521Z,"java.nio.file.FileSystemException: /home/users/Pmsx_3.3/system/bin/dbie.log: Zu viele offene Dateien","x0x4001.nbg"
```
or like this:
```
2015-07-01T07:21:25.326Z,"2015-07-01T09:17:21.587+0200 ERROR [FileObserver] collector.file.FileReaderService - Cannot read newly created file /home/users/Pmsx_3.3/system/bin/timesr.log","x0x4001.nbg"
"2015-07-01T07:21:25.326Z,""	at sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:195) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:21:25.326Z,""	at org.graylog.collector.file.FileReaderService.followFile(FileReaderService.java:130) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:21:25.326Z,""	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [graylog-collector.jar:?]"",""x0x4001.nbg"""
"2015-07-01T07:21:25.326Z,""	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:21:25.326Z,""	at sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:195) ~[?:1.7.0_21]"",""x0x4001.nbg"""
"2015-07-01T07:21:25.326Z,""	at org.graylog.collector.file.FileReaderService.access$400(FileReaderService.java:41) ~[graylog-collector.jar:?]"",""x0x4001.nbg"""
2015-07-01T07:21:25.326Z,"2015-07-01T09:17:21.588+0200 ERROR [FileObserver] collector.file.FileReaderService - Cannot read modified file /home/users/Pmsx_3.3/system/bin/qlibri.log","x0x4001.nbg"
```

**Comment by bernd** [comment]
```
2015-07-01T07:24:17.521Z,"java.nio.file.FileSystemException: /home/users/Pmsx_3.3/system/bin/dbie.log: Zu viele offene Dateien","x0x4001.nbg"
```

This sounds like you are running into the max open file limit for the user that runs the collector process.

Can you please post the output of `cat /proc/<pid>/limits`? Please replace the `<pid>` with the PID number of the collector process. This returns the limits for the collector process and should show the "Max open files" limit. Thanks!

**Comment by plt-sun** [comment]
the user is running as root. i checked all open file limits:
![zwischenablage-2](https://cloud.githubusercontent.com/assets/12797420/8452645/07d3f4c8-1fed-11e5-88bb-329a45f35f39.jpg)

**Comment by bernd** [comment]
Thanks for the feedback! I will try to reproduce this.

**Comment by bernd** [comment]
I am able to reproduce this and am currently working on a fix.

**Comment by bernd** [comment]
Please try version 0.3.0 to see if this is fixed now.

* https://github.com/Graylog2/collector/blob/master/CHANGELOG.md#v030-2015-07-14
* https://packages.graylog2.org/releases/graylog-collector/graylog-collector-0.3.0.tgz
* https://packages.graylog2.org/releases/graylog-collector/graylog-collector-0.3.0.zip

I am closing this issue now, please re-open if you still see the problem with 0.3.0. Thank you!
