### ISSUE TITLE
crash is hostname has hyphen in host name

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/collector#54]
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.net.UnknownHostException: proxy-xxx: proxy-xxx: Nome o servizio sconosciuto
  at org.graylog.collector.heartbeat.CollectorRegistrationRequestProvider.<init>(CollectorRegistrationRequestProvider.java:29)
  while locating org.graylog.collector.heartbeat.CollectorRegistrationRequestProvider
  while locating org.graylog.collector.heartbeat.CollectorRegistrationRequest
    for parameter 1 at org.graylog.collector.heartbeat.HeartbeatService.<init>(HeartbeatService.java:45)
  while locating org.graylog.collector.heartbeat.HeartbeatService
  while locating com.google.common.util.concurrent.Service annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=13, type=MULTIBINDER, keyType=)
  at org.graylog.collector.guice.CollectorModule.registerService(CollectorModule.java:41) (via modules: org.graylog.collector.buffer.BufferModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<com.google.common.util.concurrent.Service>
    for parameter 0 at org.graylog.collector.services.ServiceManagerProvider.<init>(ServiceManagerProvider.java:33)
  while locating org.graylog.collector.services.ServiceManagerProvider
  while locating com.google.common.util.concurrent.ServiceManager
    for parameter 0 at org.graylog.collector.services.CollectorServiceManager.<init>(CollectorServiceManager.java:31)
  while locating org.graylog.collector.services.CollectorServiceManager

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at org.graylog.collector.cli.commands.Run.run(Run.java:62)
        at org.graylog.collector.cli.Main.main(Main.java:50)
Caused by: java.net.UnknownHostException: proxy-xxx: proxy-xxx: Nome o servizio sconosciuto
        at java.net.InetAddress.getLocalHost(InetAddress.java:1494)
        at org.graylog.collector.heartbeat.CollectorRegistrationRequestProvider.<init>(CollectorRegistrationRequestProvider.java:31)
        at org.graylog.collector.heartbeat.CollectorRegistrationRequestProvider$$FastClassByGuice$$89039544.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:375)
        at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:258)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        ... 3 more
Caused by: java.net.UnknownHostException: proxy-bazoli: Nome o servizio sconosciuto
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1314)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1490)
        ... 40 more

**Comment by joschi** [comment]
Does the host with the name "proxy-bazoli" exist and can the system you're running the Graylog Collector on resolve that name? You can check that by running `host proxy-bazoli` or `nslookup proxy-bazoli`.

**Comment by andreaconsadori** [comment]
i change the name but issue persist.
root@proxybazoli:~# hostname
proxybazoli

**Comment by joschi** [comment]
Is the hostname resolvable?

**Comment by andreaconsadori** [comment]
hostname was missing from hosts file, now the issue stop
