### ISSUE TITLE
Cannot read modified file /var/log/syslog java.nio.file.AccessDeniedException: /var/log/syslog

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/collector#64]
```
2015-10-16T11:28:30.389+0200 ERROR [FileObserver] collector.file.FileReaderService - Cannot read modified file /var/log/syslog
java.nio.file.AccessDeniedException: /var/log/syslog
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.7.0_79]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.7.0_79]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.7.0_79]
        at sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:196) ~[?:1.7.0_79]
        at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248) ~[?:1.7.0_79]
        at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:300) ~[?:1.7.0_79]
        at org.graylog.collector.file.ChunkReaderScheduler.followFile(ChunkReaderScheduler.java:85) ~[graylog-collector.jar:?]
        at org.graylog.collector.file.ChunkReaderScheduler.followFile(ChunkReaderScheduler.java:73) ~[graylog-collector.jar:?]
        at org.graylog.collector.file.FileReaderService$FsChangeListener.pathModified(FileReaderService.java:161) [graylog-collector.jar:?]
        at org.graylog.collector.file.FileObserver$WatchPath.dispatchEvent(FileObserver.java:75) [graylog-collector.jar:?]
        at org.graylog.collector.file.FileObserver.run(FileObserver.java:142) [graylog-collector.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [graylog-collector.jar:?]
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [graylog-collector.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]'''
```

**Comment by andreaconsadori** [comment]
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK Server VM (build 24.79-b02, mixed mode)

**Comment by andreaconsadori** [comment]
where i've the issue ie see this strange behaviour

ps aux | grep collec

graylog+  7214  1.8  0.6 308628 70060 ?        Ssl  14:29   0:03 /usr/bin/java -Xms12m -Xmx64m -Djava.library.path=/usr/share/graylog-collector/lib/sigar -Dlog4j.configurationFile=/etc/graylog/collector/log4j2.xml -jar /usr/share/graylog-collector/graylog-collector.jar run -f /etc/graylog/collector/collector.conf
root      7319  2.1  0.6 311072 72152 pts/1    Sl   14:29   0:03 /usr/bin/java -Xms12m -Xmx64m -Djava.library.path=/usr/share/graylog-collector/lib/sigar -Dlog4j.configurationFile=/etc/graylog/collector/log4j2.xml -jar /usr/share/graylog-collector/graylog-collector.jar run -f /etc/graylog/collector/collector.conf

so graylog+ user don't have the permision to see /var/log files

on other system i've only one process
root     20640  0.2  1.6 239692 68436 pts/0    Sl   set30  49:48 /usr/bin/java -Xms12m -Xmx64m -Djava.library.path=/usr/share/graylog-collector/lib/sigar -Dlog4j.configurationFile=/etc/graylog/collector/log4j2.xml -jar /usr/share/graylog-collector/graylog-collector.jar run -f /etc/graylog/collector/collector.conf

**Comment by andreaconsadori** [comment]
i think is something related to new debian8 systemd

**Comment by andreaconsadori** [comment]
fixing user to root is ok

**Comment by eorochena** [comment]
I had the same exact issue on Ubuntu 14.04, I had to usermod -g adm graylog-collector to work around the issue

**Comment by joschi** [comment]
I'm closing this issue because the described problem is basically just a permission problem and not specific to the Graylog Collector.
