### ISSUE TITLE
collector.file.ChunkReader - Unable to allocate buffer

### ISSUE THREAD

**Issue by osztrovszky** [Graylog2/collector#65]
Hello Guys!
I have a big 230 MB log file.
Once I could import it with collector successfully.
Now I modified it and I'd like to import is again.

Collector giving me this error in the collector.log:
```
2015-10-21T16:32:52.127+0200 ERROR [chunkreader-scheduler-thread-local-json-0] collector.file.ChunkReader - Unable to allocate buffer
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:658) ~[?:1.8.0_66-internal]
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:1.8.0_66-internal]
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_66-internal]
        at org.graylog.collector.file.ChunkReader.run(ChunkReader.java:145) [graylog-collector.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_66-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_66-internal]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
```
Can you help me?

Cheers, 
Zsolt

**Comment by bernd** [comment]
Can you show us your collector configuration? That makes it easier to reproduce this. Thank you!

**Comment by osztrovszky** [comment]
I found out I hadn't have enough heap memory.
I've set the heap size larger, now everything works fine.
Thanks,
Zsolt

On Wed, Oct 28, 2015, 08:49 Bernd Ahlers <notifications@github.com> wrote:

> Can you show us your collector configuration? That makes it easier to
> reproduce this. Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/collector/issues/65#issuecomment-151755115>.
>
-- 
Üdv:
Osztrovszky Zsolt

**Comment by bernd** [comment]
Thanks for the feedback!
